export const rows = [
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  },
  {
    address: "7no ward office",
    name: "Ash",
    priority: 'high',
    complaintId: "C2KM/E/2024/680",
    date: "8:08 PM 15th Feb, 2024",
    department: "Electric",
    description: "7no ward office Hai mast not working",
    location: "7 no ward office",
    medias: [],
    status: {
      Completed: "",
      Completed_date: "2:59 PM 22nd Feb, 2024",
      In_Progress: "",
      In_Progress_date: "10:03 AM 18th Feb, 2024",
      Initiated: "",
      Initiated_date: "",
      Reject: "",
      Reject_date: ""
    },
    subject_type: "Others Street Light Off",
    title: "Hai mast not working",
    id: "KhDapFdd4fVJlz2pMJysgBa3Nau1",
    updated_at: "22 February 2024 at 14:59:45 UTC+5:30",
    ward: "7"
  }
];



export const users = [
  {
    id: "1",
    "name": "John Doe",
    "address": "123 Main Street",
    "date": "2024-03-10",
    "department": "Human Resources",
    "status": "Active",
    "phone_no": "123-456-7890",
    "role": "admin",
    email: 'john@gmail.com'
  },
  {
    id: "2",
    "name": "Jane Smith",
    "address": "456 Elm Street",
    "date": "2024-03-11",
    "department": "Marketing",
    "status": "Active",
    "phone_no": "987-654-3210",
    "role": "superadmin",
    email: 'jane@gmail.com'
  },
  {
    id: "3",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "4",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "5",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "6",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "7",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "8",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "9",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "10",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
  {
    id: "11",
    "name": "Michael Johnson",
    "address": "789 Oak Street",
    "date": "2024-03-12",
    "department": "Finance",
    "status": "Active",
    "phone_no": "555-123-4567",
    "role": "agent",
    email: 'michael@gmail.com'
  },
];

export const report = [
  {
    "id": 1,
    "Period": "All time",
    "Created_at": "2024-01-01T08:00:00Z",
    "Action": "Edit"
  },
  {
    "id": 2,
    "Period": "Whole year",
    "Created_at": "2024-02-15T10:30:00Z",
    "Action": "Delete"
  },
  {
    "id": 3,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
  {
    "id": 4,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
  {
    "id": 5,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
  {
    "id": 6,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
  {
    "id": 7,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
  {
    "id": 8,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
  {
    "id": 9,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
  {
    "id": 10,
    "Period": "last Month",
    "Created_at": "2024-03-05T14:45:00Z",
    "Action": "View"
  },
]

export const email = [
  {
    id: "1",
    title: "Email Verification",
    hook: "email_verification",
    language: "English",
    updated_at: "Never Updated",
    created_at: "07/03/2024",
    actions: "Edit",
  },
  {
    id: "2",
    title: "Forget Password",
    hook: "forget_password",
    language: "English",
    updated_at: "Never Updated",
    created_at: "07/03/2024",
    actions: "Edit",
  },
  {
    id: "3",
    title: "Email Verification",
    hook: "email_verification",
    language: "English",
    updated_at: "Never Updated",
    created_at: "07/03/2024",
    actions: "Edit",
  },
  {
    id: "4",
    title: "Email Verification",
    hook: "email_verification",
    language: "English",
    updated_at: "Never Updated",
    created_at: "07/03/2024",
    actions: "Edit",
  },
  {
    id: "5",
    title: "Email Verification",
    hook: "email_verification",
    language: "English",
    updated_at: "Never Updated",
    created_at: "07/03/2024",
    actions: "Edit",
  },
];